version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: cookiemonster
    volumes:
      - db:/var/lib/postgresql/data

  vcsserver:
    image: ckulka/rhodecode-vcsserver
    volumes:
      - repos:/data

  rhodecode:
    image: ckulka/rhodecode-ce
    environment:
      RC_DB: postgresql://postgres:cookiemonster@db
    ports:
      - "5000:5000"
    links:
      - db
      - vcsserver
    volumes:
      - repos:/data

volumes:
  repos:
  db:
